### ISSUE TITLE
Exception with cmake project

### ISSUE THREAD

**Issue by venkatmakam** [n0lavar/DoxygenComments#1]
hello,
I got the following exception when I tried to generate function header for a sample cmake project.

```
---------------------------
Microsoft Visual Studio
---------------------------
DoxygenComments

An exception was thrown :

Value cannot be null.

Parameter name: FileCodeModel

   at DoxygenComments.AltTCommand.CreateComment() in D:\Mega\programming\TheGame\qxProject\DoxygenComments\Project\AltTCommand.cs:line 286

   at DoxygenComments.AltTCommand.Execute(Object sender, EventArgs e) in D:\Mega\programming\TheGame\qxProject\DoxygenComments\Project\AltTCommand.cs:line 177
---------------------------
OK   
---------------------------
```

**Comment by n0lavar** [comment]
Hello
Looks like this file isn’t in your project and extension can’t find it
through Visual Studio API
Check you have added file in cmake and try to rerun it

**Comment by n0lavar** [comment]
If you still receive this error, please provide minimal reproducible example

**Comment by venkatmakam** [comment]
[test.zip](https://github.com/n0lavar/DoxygenComments/files/7225461/test.zip)
Hi, please find the cmake project

**Comment by n0lavar** [comment]
cmake .
Project.sln
Alt+T for header, testfun and main
looks like correct output
```
/**

    @file      test.cpp
    @author    Khrapov
    @date      24.09.2021
    @copyright © Nick Khrapov, 2021. All right reserved.

**/
#include <qxe/core/stdafx.h>


#include "stdafx.h"

/**
    @brief  
    @param  a - 
    @param  b - 
    @retval   - 
**/
int testfun(int a, int b)
{

}

/**
    @brief  
    @retval - 
**/
int main() //!< 
{

	return 0;
}
```
please note that only VS 2019 is fully supported, I have not tested other versions

**Comment by n0lavar** [comment]
also nothing before this line of code depends on settings

**Comment by venkatmakam** [comment]
I am not generating sln files directly, instead I am using Visual studio CMake tools (https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160) . So, I am opening the folder directly in visual studio and CMakeSettings.json to configure the project. I tried both Ninja and Visual Studio 2019 generators.

**Comment by n0lavar** [comment]
I reproduced your problem.
According to wiki page you provided:
> The C++ CMake tools for Windows component uses the Open Folder feature to consume CMake project files (such as CMakeLists.txt) directly for the purposes of IntelliSense and browsing. Both Ninja and Visual Studio generators are supported. If you use a Visual Studio generator, it generates a temporary project file and passes it to MSBuild. **However, the project is never loaded for IntelliSense or browsing purposes.** 

I have not worked with this utility, but it seems the problem is that a temporary project is being used with no browser access. I don't think I can do anything about it from the extension side.
I advise you to use the cmake manually.
