### ISSUE TITLE
Option to use `@return` keyword in place of `@retval`

### ISSUE THREAD

**Issue by jwfxpr** [n0lavar/DoxygenComments#2]
I've recently joined a large project for a client with some very specific and unusual code styles, among which is a mix of JavaDoc, Qt and Doxygen styles for documentation comments. They require the use of the `@return` keyword, rather than the `@retval` keyword which is the DoxygenComments default.

I haven't been able to find an option for using the `@return` keyword in the extension. Am I missing something? Or if it's currently not an option, can it be implemented easily? There's no need to change the semantics, it can simply replace `@retval` with `@return`, that's fine.

**Comment by n0lavar** [comment]
Welcome
It’s pretty easy to implement, but I don’t have much time at the moment
Also I have to test 2022 build before release a bit more
I’ll add this option in todo list and notify you when it’s ready

Чт, 10 марта 2022 г. в 17:51, John Reid ***@***.***>:

**Comment by n0lavar** [comment]
You can find this option in the Common settings section in version 1.4
