### ISSUE TITLE
Value cannot be null. Parameter name: FileCodeModel

### ISSUE THREAD

**Issue by ifknot** [n0lavar/DoxygenComments#5]
Hi, using:

Microsoft Visual Studio Community 2019 Version 16.11.15 VisualStudio.16.Release/16.11.15+32510.428
Microsoft .NET Framework Version 4.8.04084

I get this error:

> DoxygenComments
> 
> An excpetion was thrown:
> 
> Value cannot be null.
> Parameter name: FileCodeModel
> 
>   at DoxygenComments.AltTCommand.CreateComment() in
> AltTCommand.cs:line 329
>   at DoxygenComments.AltTCommand.Execute(Object sender, 
> EventArgs e) in AltTCommand.cs:line 190

Is there a fix?

thanks

**Comment by n0lavar** [comment]
Hello
Please check if this file is in solution (eg you can find file in solution explorer)

**Comment by ifknot** [comment]
solved: yes visible but lost my .sln with git.ignore so editing as a folder - fixed now 

speedy respone many thanks
