### ISSUE TITLE
Value Cannot be Null: FileCodeModel

### ISSUE THREAD

**Issue by AhmedAredah** [n0lavar/DoxygenComments#6]
![image](https://user-images.githubusercontent.com/77444744/218852424-2f969af4-1f77-4dc4-bcd0-b1cb1bab681e.png)

**Comment by n0lavar** [comment]
You should add the file you working in to your solution (via cmake or manually)

**Comment by rapperskull** [comment]
> You should add the file you working in to your solution (via cmake or manually)

Is there any way to avoid this? I'm using Visual Studio only as an editor and I don't have any solution configured.

**Comment by n0lavar** [comment]
I'm afraid no
Extension use VS API to find C++ entities
Using this I can only use files included in solution
Otherwise I will have to write my own parser
