### ISSUE TITLE
Excuse me! Type /** Can not input file header comments in vs2022

### ISSUE THREAD

**Issue by ShuiYunXi** [n0lavar/DoxygenComments#7]
The doxygencomments related plugins are incomplete. When I use doxygencomments to annotate my files, using /** does not appear in the file header corresponding to the comments. But /** is fine when used in a function.

**Comment by ShuiYunXi** [comment]
Please tell me how to fix it. thanks!

**Comment by n0lavar** [comment]
Hello @ShuiYunXi 
You should use Alt+T shortcut to create a comment
