### ISSUE TITLE
DoxygenComments does crash on CMake projects

### ISSUE THREAD

**Issue by ggs67** [n0lavar/DoxygenComments#8]
DoxygenCommentscrashes with "value cannot be null FileCodeModel" after Alt-T command on anything except file comment on a CMake project. When I move the same file (C++ header file in this case) to a VS native solution project, ALT-T works fine.

I think that the reason is the missing file properties in CMake projects.

**Comment by n0lavar** [comment]
I use API that is provided by VS and I have no idea why cmake projects works that way. Unfortunally, there is nothing I can do from my side, and this issue is an expected behaviour right now.
