### ISSUE TITLE
Exception when using DoxygenComments-Plugin in VS 2022 (Version 17.7.6)

### ISSUE THREAD

**Issue by NikFri94** [n0lavar/DoxygenComments#9]
Hey,
when trying to insert a new Doxygen Comment except file comments, i reciev following exception:
![grafik](https://github.com/n0lavar/DoxygenComments/assets/139549862/8a41acc7-8e42-4923-bd35-cd6d568a820f)

The only comments which can be inserted properly are the file related comments:
![grafik](https://github.com/n0lavar/DoxygenComments/assets/139549862/b9f34c99-4198-4f03-be7d-21fbe868b105)

It would be nice if you know a workaround for this issue.

**Comment by n0lavar** [comment]
Hello [Niklas](https://github.com/NikFri94),

Usually this is because of external files. To be able to use a plugin you should include a file into your solution. Add it into your cmakelists if you are using cmake or into a soulution directly.

**Comment by NikFri94** [comment]
This does not seem to make any difference :/

**Comment by n0lavar** [comment]
I need a minimal reproducible example then

**Comment by NikFri94** [comment]
I have uploaded a minimal example in this repo:
https://github.com/NikFri94/Doxygen_bug_example

If i try to add a Doxygen comment for the main function, in app/src/main.cpp i recieve the error from above:
![grafik](https://github.com/n0lavar/DoxygenComments/assets/139549862/434c5f62-9661-450f-a9b3-6023fdc0253c)

**Comment by zecuse** [comment]
I've run into the same problem. The files I'm trying to document are all part of the same small cmake project (C++) which is a subproject of a larger one that's currently not doing anything else. Everything that's relevant to this project can be found [here](https://github.com/zecuse/Algorithms/tree/DeltaTime/DeltaTime/C%2B%2B).

**Comment by jeff-kohn** [comment]
Still seeing this issue. Anybody get this to work with a CMake project?

**Comment by n0lavar** [comment]
I downloaded your repo, generated sln and and it works fine.
Please make sure that all the files you are working with are in your solution, otherwise VS won't be able to generate a model for them and I won't be able to use them.
![image](https://github.com/user-attachments/assets/c5373c84-2c60-4006-92b4-1213934ff64b)

**Comment by jeff-kohn** [comment]
> I downloaded your repo, generated sln and and it works fine. Please make sure that all the files you are working with are in your solution, otherwise VS won't be able to generate a model for them and I won't be able to use them.

So you're saying only SLN project are supported, not CMake (e.g. Open Folder)? If so you might want to update your readme with that information to avoid future confusion.

**Comment by n0lavar** [comment]
Makes sense, will do

**Comment by n0lavar** [comment]
Done https://github.com/n0lavar/DoxygenComments/commit/fef60f158c82d67cb228de72e243a9bc4e4969fb
